### PR TITLE
Next release of rstantools

### PR DESCRIPTION
**Pull request by jgabry**
Sorry the delay on this! CRAN has requested a new release of rstantools before March 16th (for reasons unrelated to the functionality of the package, just to fix an issue with the doc). But we'll include all PRs merged since the previous release in this new release. A few things: 

@bgoodri @andrjohns @hsbadr Do any of you have anything else that needs to be done in rstantools before the release? Or can I go ahead and submit? Also, Hamada and Andrew, can I add you to the list of official contributors to the package? You've both been super helpful!

### CODE REVIEW

**Comment by andrjohns** [comment]
Great to hear! Sorry that I missed this! Nothing from my end, and of course very happy to be added as a contributor

**Comment by andrjohns** [comment]
Actually scratch that sorry, there needs to be a minor change for compatibility with the use of `.stanfunctions` files (files containing only function definitions, but without the enclosing `functions { }` ). I'll work that up today

**Comment by hsbadr** [comment]
> Also, Hamada and Andrew, can I add you to the list of official contributors to the package?

I'd be happy to be a contributor too.

I don't have any requests for this release. I've been using it in my development environment. It'd be nice to support `.stanfunctions` files in this release, as @andrjohns suggested and opened a PR.

**Comment by jgabry** [comment]
Ok great, I'll go ahead and submit the release once #94 is merged (just waiting to see if @bgoodri wants to take a look at that before I merge it). 

Thanks again to you both for your help!

**Comment by jgabry** [comment]
Actually I might as well also deal with #89 (not using travis) in this release. Will deprecate the `travis` argument to `rstan_create_package` (and change the default to FALSE) and then we can eventually remove that argument entirely in a future release.

**Comment by jgabry** [comment]
@bgoodri @hsbadr @andrjohns Just submitted to CRAN now

**Pull request merged**
