### PR TITLE
rstantools v2.0.0 (with all @mlysy's stuff)

### PR DESCRIPTION
**Pull request by bgoodri**
this is really just a few changes and fixes of merge conflicts on top of
https://github.com/stan-dev/rstantools/pull/34

### CODE REVIEW

**Comment by mlysy** [comment]
A few other changes come to mind regarding the latest changes to `src/Makevars[.win]` for CRAN compatibility discussed [here](https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto/6041):

- `inst/include/sys/Makevars[.win]` needs to be updated.
- User packages will need to add `SystemRequirements: GNU make` to the `DESCRIPTION`.

    This can be done directly from within `update_description()`, but I was thinking that a more forward-looking solution would be to have `update_description()` make `DESCRIPTION` compatible with whatever is listed in `inst/include/sys/DESCRIPTION`, and put the `SystemRequirements` line there.

Happy to make these modifications myself.  If that's OK, should I just merge the changes from this branch back into `mlysy/rstantools/rstantools_patch` and do the updates there?

**Comment by mlysy** [comment]
Actually, quoting [this](https://cran.r-project.org/doc/manuals/R-exts.html#Writing-portable-packages) section of Writing R Extensions:

> Since the only viable make for Windows is GNU make, it is permissible to use GNU extensions in files Makevars.win or Makefile.win.

Therefore, it appears that `SystemRequirements: GNU make` is in fact not necessary (passed `R CMD check` without it on my OSX and winbuilder).

**Comment by bgoodri** [comment]
For src/Makevars.win that is true. But if there is no

SystemRequirements: GNU make

in DESCRIPTION, then R CMD check will issue a WARNING on Linux due to
src/Makevars utilizing GNU make extensions. On Macs, I have seen
conflicting reports of whether there is a WARNING about that.

I can push all of the changes you suggested.

**Comment by mlysy** [comment]
Sorry I misread the manual as stating `Makevars` and `Makevars.win`...

**Comment by jgabry** [comment]
This looks good to me. Is this ready to merge or are there still a few things to be pushed?

**Comment by mlysy** [comment]
I don't think the changes I suggested above (update `Makevars[.win]` and `SystemRequirements: GNU make`) have been pushed yet...

**Comment by hhau** [comment]
Unsure where to leave this comment, but the version of `rstan_create_package` in c3c59fb does not work if the package directory is a subdirectory of a filepath that has spaces in it.  I can't find where it happens, but the system call to CHMOD that is intended to make `configure`/`configure.win` executable fails, so when you try to run `pkgbuild::compile_dll` (per #52), you get:

```
> rstantools::rstan_create_package(
+   path = "teststanpkg"
+ )
Creating package skeleton for package: teststanpkg
✔ Creating 'teststanpkg/'
✔ Setting active project to '/Users/amanderson/OneDrive - The Alan Turing Institute/PhD/Projects/2019-03-07_wde-tools/teststanpkg'
✔ Creating 'R/'
✔ Creating 'man/'
✔ Writing 'DESCRIPTION'
Package: teststanpkg
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre]
Description: What the package does (one paragraph).
License: What license it uses
Encoding: UTF-8
LazyData: true
✔ Writing 'NAMESPACE'
✔ Writing 'teststanpkg.Rproj'
✔ Adding '.Rproj.user' to '.gitignore'
✔ Adding '^teststanpkg\\.Rproj$', '^\\.Rproj\\.user$' to '.Rbuildignore'
✔ Setting active project to '<no active project>'
Adding .travis.yml file ...
Creating inst/stan/include directory ...
Creating inst/include directory ...
Creating src directory ...
Updating DESCRIPTION ...
Adding 'configure' files ...
chmod: /Users/amanderson/OneDrive: No such file or directory
chmod: -: No such file or directory
chmod: The: No such file or directory
chmod: Alan: No such file or directory
chmod: Turing: No such file or directory
chmod: Institute/PhD/Projects/2019-03-07_wde-tools/teststanpkg/configure: No such file or directory
chmod: /Users/amanderson/OneDrive: No such file or directory
chmod: -: No such file or directory
chmod: The: No such file or directory
chmod: Alan: No such file or directory
chmod: Turing: No such file or directory
chmod: Institute/PhD/Projects/2019-03-07_wde-tools/teststanpkg/configure.win: No such file or directory
Updating NAMESPACE ...
Done.
Adding teststanpkg-package.R file ...
Configuring Stan compile and module export instructions ...
Further Stan-specific steps are described in 'teststanpkg/Read-and-delete-me'.
> pkgbuild::compile_dll("teststanpkg/")
Re-compiling teststanpkg
─  installing *source* package ‘teststanpkg’ ...
   ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
─  removing ‘/private/var/folders/9q/xrp79_nd2d7dhnp5j6nncymd6zq2rx/T/RtmplvZDer/devtools_install_23b3855f900/teststanpkg’
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
``` 

I have tested that it works in a directory where the normalised path does not contain spaces.

**Comment by mlysy** [comment]
Thanks for catching this.  Should be fixed now [here](https://github.com/mlysy/rstantools/tree/rstantools_patch).

@jgabry and @bgoodri: I've made the `Makevars[.win]` and `SystemRequirements` discussed above, as well as some minor modifications regarding the devtools v2 ecosystem.

**Comment by jgabry** [comment]
I did a bit of doc cleanup and also got rid of `rstan_package_skeleton` on this branch (still need to merge #53 into this branch). @mlysy We'll also need to update your new tests to get rid of testing `rstan_package_skeleton` and just use `rstan_create_package` (I haven't done that yet).

**Comment by jgabry** [comment]
I also bumped the version to 2.0.0 since this will be a major release

**Comment by jgabry** [comment]
@mlysy Thanks again for all your work on this. It all seems to work great, except for the vignette. Does the vignette build successfully for you? For me it fails unless I insert `pkgbuild::compile_dll` before `roxygen2::roxygenize`, but shouldn't it be unnecessary for the user to do that (i.e., shouldn't that be happening automatically)?

**Comment by mlysy** [comment]
@jgabry sorry for the slow response...

I believe this is now necessary for packages with `src` code and newer versions of roxygen2/devtools: https://github.com/klutometis/roxygen/issues/822#issuecomment-441425591.

**Comment by jgabry** [comment]
Ok thanks. I can update the vignette. Do you mind updating your tests to remove `rstan_package_skeleton` and fix anything else (if necessary)?

**Comment by mlysy** [comment]
Done.  Also made minor change package vignette as above so as to pass `devtools::check(run_dont_test = TRUE)` without notes/errors.

**Comment by jgabry** [comment]
Great, thanks! Merged.

**Comment by jgabry** [comment]
@mlysy I'm getting some errors from the `rstan_create_package` and `rstan_config` tests.  

Here's the failure from  the `rstan_config` tests (there are several similar ones):
```r
...
test-rstan_config.R:65: failure: Stan src files are created properly
readLines(src_files[1]) not identical to readLines(src_files[2]).
Lengths differ: 329 is not 306
```

I think it's because the src files stored in [tests/testthat/RStanTest](https://github.com/stan-dev/rstantools/tree/mlysy-rstantools_patch/tests/testthat/RStanTest) were created with a specific version of RStan you had installed when you created them. The tests comparing src files will fail unless that same version of RStan is installed on the testing system. 

For `rstan_create_package` I'm not seeing a test failure but I get this from the `-- without roxygen` case: 
```
...
✔ Writing 'NAMESPACE'
Loading required package: RStanTest
Error in .requirePackage(package) : 
  unable to find required package 'RStanTest'
Calls: <Anonymous> -> $ -> $ -> is -> getClassDef -> .requirePackage
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'RStanTest'
```

**Comment by mlysy** [comment]
Hi @jgabry, I'll try to fix these asap...

**Comment by mlysy** [comment]
@jgabry just wanted to touch base.  My day job has required most of my attention these last two weeks so I haven't been able to work on this as much as I would like.  

For the `rstan_config` issue, I used [`testthat::expect_known_output`](https://testthat.r-lib.org/reference/expect_known_output.html) to compare the newly-generated `.cc`/`.h` files against those on record.  However, this still produces failures whenever the Stan C++ code changes, so the test is just disabled by default.

For the `rstan_create_package` issue, I'm not sure what the problem is yet.  It seems to be coming from `pkgload::load_all` having difficulty loading/unloading a package of which the internals are quite different...

**Comment by jgabry** [comment]
@mlysy no worries, thanks for the update. If the the only problem is testing then I think we can move forward and then enable the tests whenever you have time. Do you think everything outside the tests is ready?

**Comment by jgabry** [comment]
@mlysy just double checking, do you agree that the problematic tests don’t actually indicate any issues with the implementation? That is, we just need to figure out how to test it but you’re ok with everything else?

**Comment by jgabry** [comment]
And @bgoodri does any config stuff in this PR need to change in anticipation of RStan 2.19?

**Comment by mlysy** [comment]
@jgabry sincere apologies for the slow response.  I can confirm that the error messages do not break the tests (seem to be a strange interaction between `roxygenize` and `load/unload_all`...)

I've just made a PR with my other commits (regarding `rstan_config`).

**Comment by bgoodri** [comment]
I don't think the config needs any changes.

**Comment by jgabry** [comment]
Ok I'm going to merge this and @bgoodri we should talk about a release date that we can coordinate with rstanarm.

**Pull request merged**
