### PR TITLE
rstantools v2.4.0

### PR DESCRIPTION
**Pull request by jgabry**
Getting ready for the next release.

### CODE REVIEW

**Comment by jgabry** [comment]
@andrjohns I'll run reverse dependency checks locally and if those pass and so do all the checks for this PR then I'll go ahead and submit to CRAN.

**Comment by jgabry** [comment]
@andrjohns Do you by any chance have any time to help look into these multiple GHA failures? I've got a ton to catch up on after being away for a while so it might take me some time to get to this.

**Comment by andrjohns** [comment]
> @andrjohns Do you by any chance have any time to help look into these multiple GHA failures? I've got a ton to catch up on after being away for a while so it might take me some time to get to this.

Perfect timing! I'm waiting for some other stuff to finish running, so I can have a look now

**Comment by jgabry** [comment]
@andrjohns A few things: 

1. Looks like your commit fixed the Stanfunctions support checks (thanks!), but there's still a failure on Ubuntu with R-devel. It looks like it's erroring in the vignette, but I tried to reproduce the error and I haven't been able to. Any ideas? If not I can try to do some more digging. 

2. I ran reverse dependency checks on the 100+ packages that use rstantools and they all passed, so we're good to go other than the weird vignette/Ubuntu failure.

**Comment by andrjohns** [comment]
>     2. I ran reverse dependency checks on the 100+ packages that use rstantools and they all passed, so we're good to go other than the weird vignette/Ubuntu failure.

Yeww! Great to hear. I'm also having trouble replicating the Ubuntu devel failure, but I want to dig a little more. Could you try submitting to the win-builder devel and see if there's an error there too?

**Comment by andrjohns** [comment]
@jgabry figured it out. For some reason some of the example code in `example(source)` was throwing an error. But since that was only being called so that the `sourceDir` function was defined, we can instead just define that directly

**Comment by jgabry** [comment]
Awesome, thanks for figuring that out and fixing it

**Comment by jgabry** [comment]
I'll go ahead and submit to CRAN

**Comment by jgabry** [comment]
On CRAN now

**Pull request merged**
