### PR TITLE
Rstantools patch

### PR DESCRIPTION
**Pull request by mlysy**
Update to PR #44.

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks for this! Sorry we’ve been slow on this. Busy times. @bgoodri we should meet soon to get this stuff released.

**Comment by mlysy** [comment]
Very glad to hear this!  One minor pre-release comment:

Currently we offer `rstan_package_skeleton` and `rstan_create_package` as two methods of doing almost exactly the same thing.  I'll go back on my earlier words and suggest that we offer only the latter approach.  `utils::package_skeleton` (on which `rstan_package_skeleton` is built) doesn't always behave as "expected".  Currently it will produce an error if no R functions are provided and the workspace is empty.  If no R functions are provided but the workspace is not empty, it will dump in all objects in the workspace, including sometimes the random seed!  So why not simplify things and depreciate `rstan_package_skeleton`? :)

**Comment by jgabry** [comment]
I’d be ok with deprecating it. @bgoodri?

**Comment by bgoodri** [comment]
If we think people should only be using rstan_create_package, then I would
favor getting rid of rstan_package_skeleton. No one should have a script
that calls rstan_package_skeleton and would thus get broken if we do so.

**Comment by jgabry** [comment]
True, it would certainly be strange to be calling `rstan_package_skeleton` inside any sort of script.

**Comment by jgabry** [comment]
Ok, I think we can merge this first and then take care of `rstan_package_skeleton`. I've gone through this PR and it seems good to me. It's going into stan-dev:mlysy-rstantools_patch and not master so I think we should go ahead and merge this into that branch and then we'll take care of remaining details there before merging into master. @bgoodri Does that seem reasonable? If so, I'll go ahead and do that.

**Comment by jgabry** [comment]
I'm just going to go ahead and merge this and let's continue the discussion over at #44 since I already did the `rstan_package_skeleton` removal and other stuff over there

**Pull request merged**
