### PR TITLE
feature suggestions for rstan_package_skeleton

### PR DESCRIPTION
**Pull request by mlysy**
Dear @jgabry and @bgoodri,

Thanks for your patience while I worked through this PR for #30.  Most of the time was actually spent writing unit tests to make sure the packages output by `rstan_package_skeleton` work as expected across platforms.  

A summary of added features is listed in a package skeleton [README](https://github.com/mlysy/rstantools/blob/rstantools_patch/README_package_skeleton.md), aside from which the only changes should be (i) the addition of `testthat` unit tests and (ii) minor modifications to the `minimal-rstan-package.Rmd` vignette to reflect updates in the package creation process.

Perhaps the most pressing issue with this patch is that the mechanism for automated creation of Stan C++ files (used to be handled by running `make_cc` in `Makevars` script) will not work for CRAN submissions.  The reason for this is detailed in the package skeleton [README](https://github.com/mlysy/rstantools/blob/rstantools_patch/README_package_skeleton.md).  I don't think it will take to long to get to the bottom of this, but since I've taken so long already I figured it's probably a good time to get you to weigh in on what I've done so far :)

### CODE REVIEW

**Comment by jgabry** [comment]
@mlysy Thanks!! Will review this and get you comments as soon as possible.

**Comment by bgoodri** [comment]
Finally getting around to reading through this. We can probably merge it before the next **rstantools** release. One question I have so far is why it is using `stanc_builder` rather than `stanc`? In general, we want packages to rely on the (somewhat pedantic) `#include` mechanism in the Stan parser and `stanc_builder` will probably either be deprecated or just become an alias for `stanc` at some point soon.

**Comment by mlysy** [comment]
Hi!  The reason for using `stanc_builder` rather than `stanc` seems to be outdated.  It used to be that only the former processed the Stan `#include`s correctly, but in the latest CRAN version of `rstan` this appears to have been fixed.

Just to be sure, I'll add an `#include` unit test and check on various platforms before reissuing the pull request.

**Comment by mlysy** [comment]
I was wrong, in that `stanc` doesn't seem to process the `#include`s (neither with rstan on CRAN or GitHub "develop" branch).  Minimal example:

```stan
// --- main.stan ---
functions {
  #include "helper.stan"
}
model {}
generated quantities {
  real alpha;
  alpha = helper_fun(3.14);
}
```

```stan
// --- helper.stan ---
real helper_fun(real x) {
  return x;
}
```

```r
# R script

# works fine
cppcode <- rstan::stanc_builder("main.stan", allow_undefined = TRUE,
                                obfuscate_model_name = FALSE)$cppcode
# doesn't work
cppcode <- rstan::stanc("main.stan", allow_undefined = TRUE,
                        obfuscate_model_name = FALSE)$cppcode
```
```r
# error message

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Warning (non-fatal): Comments beginning with # are deprecated.  Please use // in place of # for line comments.
Warning (non-fatal): Comments beginning with # are deprecated.  Please use // in place of # for line comments.
No matches for: 

  helper_fun(real)

Function helper_fun not found.
  error in 'model_main' at line 9, column 27
  -------------------------------------------------
     7: generated quantities {
     8:   real alpha;
     9:   alpha = helper_fun(3.14);
                                  ^
    10: }
  -------------------------------------------------

Error in rstan::stanc("main.stan", allow_undefined = TRUE, obfuscate_model_name = FALSE) : 
  failed to parse Stan model 'main' due to the above error.
```

**Comment by mlysy** [comment]
Yup, that was it.   Switched to `stanc`, rebased upstream/master, tested with clang++ and [win-builder](https://win-builder.r-project.org/).

**Comment by mlysy** [comment]
Unfortunately the Travis CI build didn't work, but I think this is due to timeout...

**Comment by mlysy** [comment]
Hi @jgabry and @bgoodri, just checking if there's anything I can do with this PR to help you prepare for the next **rstantools** release?

**Comment by bgoodri** [comment]
It will need a bit of updating for RStan 2.18 but we can't upload that to
CRAN because it breaks other packages.

**Comment by mlysy** [comment]
OK.  Please allow me to reiterate that I'm more than happy to make any updates / changes / work on whatever else might be helpful :)

**Comment by bgoodri** [comment]
OK, at long last **rstanarm** 2.18.1 is on CRAN now and uses the C++14 syntax needed for packages that have StanHeaders in their LinkingTo. So, we should make a push to get this PR updated, merged, and released so that anyone else who is creating a Stan-based package gets the correct skeleton and configuration from the outset.

**Comment by bgoodri** [comment]
OK, at long last **rstanarm** 2.18.1 is on CRAN now and uses the C++14 syntax needed for packages that have StanHeaders in their LinkingTo. So, we should make a push to get this PR updated, merged, and released so that anyone else who is creating a Stan-based package gets the correct skeleton and configuration from the outset.

**Comment by mlysy** [comment]
Sounds great!  I'm testing the updates now, will update PR after.

**Comment by jgabry** [comment]
@mlysy Ok great! Thanks a lot for working on updating this. On our end we're ready to merge this as soon as you're ready with that.

**Comment by mlysy** [comment]
Dear @jgabry and @bgoodri, here's what I have so far.  Everything was going great until I checked with winbuilder a few days ago, and found that the new CRAN devtools required several unusual modifications to the package (see commit msgs above).  I managed to get most things to work, but `devtools::check()` fails on my system with the following error:

```r
Updating rstantools documentation
Writing NAMESPACE
Loading rstantools
Re-compiling rstantools
─  installing *source* package ‘rstantools’ ...
─  DONE (rstantools)
This is rstantools version 1.5.1.9000
Writing NAMESPACE
── Building ────────────────────────────────────────────────────── rstantools ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/Users/mlysy/Documents/R/test/rstantools/DESCRIPTION’
─  preparing ‘rstantools’: (357ms)
✔  checking DESCRIPTION meta-information
─  installing the package to build vignettes
E  creating vignettes (10.3s)
   Quitting from lines 220-221 (minimal-rstan-package.Rmd) 
   Error: processing vignette 'minimal-rstan-package.Rmd' failed with diagnostics:
   System command error
   Execution halted
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
```
Works fine with `devtools::build_vignettes()` though...here is the `sessionInfo()`:
```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstantools_1.5.1.9000 testthat_2.0.0       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19      rstudioapi_0.7    knitr_1.20        xml2_1.2.0       
 [5] magrittr_1.5      roxygen2_6.1.0    usethis_1.4.0     devtools_2.0.0   
 [9] pkgload_1.0.1     R6_2.3.0          brew_1.0-6        rlang_0.2.1      
[13] stringr_1.3.1     tools_3.5.0       pkgbuild_1.0.2    sessioninfo_1.1.0
[17] cli_1.0.0         withr_2.1.2       remotes_2.0.1     commonmark_1.5   
[21] assertthat_0.2.0  rprojroot_1.3-2   digest_0.6.15     crayon_1.3.4     
[25] processx_3.1.0    purrr_0.2.4       callr_2.0.4       clisymbols_1.2.0 
[29] fs_1.2.6          memoise_1.1.0     glue_1.2.0        stringi_1.2.2    
[33] compiler_3.5.0    desc_1.2.0        backports_1.1.2   prettyunits_1.0.2
```
Seems there's an issue with calling `devtools` from within `R CMD check` (checked that from a terminal outside of R session as well).

I would love to keep digging around, but unfortunately my day job will prevent me from doing so for the next 1-2 weeks, so I figured it's more expedient to let you folks take a look :)

**Comment by bgoodri** [comment]
Thanks. We'll look into it. It might be that we can get away with not using
devtools now that it has essentially been broken into several separate
packages.

**Pull request closed without merging**
